apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-store
  namespace: store-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-store
  chart:
    git: ssh://git@github.com/Akshatavijapur92/blockchain-automation-framework.git
    ref: master
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: store-net
      images:
        fabrictools: hyperledger/fabric-tools:1.4.4
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.store-net.fab.team19.aws.bafevent.com:8443
      localmspid: storeMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://aa2d78d17c76811eab25a02b991bc25b-1354633767.ap-south-1.elb.amazonaws.com:9000
      authpath: store-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/store-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/store-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.fab.team19.aws.bafevent.com:8443
    anchorstx: |-
      CrQCChAKDggCIgphbGxjaGFubmVsEp8CCpwCCgphbGxjaGFubmVsElgSVgoLQXBwbGljYXRpb24S
      RwgBEjsKCHN0b3JlTVNQEi8aBwoDTVNQEgAiCwoHUmVhZGVycxIAIgsKB1dyaXRlcnMSACIKCgZB
      ZG1pbnMSACoGQWRtaW5zGrMBErABCgtBcHBsaWNhdGlvbhKgAQgBEpMBCghzdG9yZU1TUBKGAQgB
      GgcKA01TUBIAGksKC0FuY2hvclBlZXJzEjwSMgowCitwZWVyMC5zdG9yZS1uZXQuZmFiLnRlYW0x
      OS5hd3MuYmFmZXZlbnQuY29tEPtBGgZBZG1pbnMiCwoHUmVhZGVycxIAIgsKB1dyaXRlcnMSACIK
      CgZBZG1pbnMSACoGQWRtaW5zKgZBZG1pbnM=

