apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: store-expressapi
  namespace: store-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  chart:
    path: platforms/hyperledger-fabric/charts/expressapp
    git: "ssh://git@github.com/Akshatavijapur92/blockchain-automation-framework.git"
    ref: "master"
  releaseName: storefabric-expressapi
  values:
    nodeName: store-expressapi
    metadata:
      namespace: store-net
    replicaCount: 1
    expressapp:
      serviceType: ClusterIP
      image: index.docker.io/hyperledgerlabs/supplychain_fabric:express_app_latest
      pullPolicy: Always
      pullSecrets: regcred
      nodePorts:
        port: 3000
        targetPort: 3000
        name: tcp
      env:
        apiUrl: http://store-restserver.store-net:20001/api/v1
    proxy:
      provider: haproxy
      name: store
      type: fabric
      external_url_suffix: fab.team19.aws.bafevent.com
      peer_name: peer0
