apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: manufacturer-restserver
  namespace: manufacturer-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  chart:
    path: platforms/hyperledger-fabric/charts/fabric-restserver
    git: ssh://git@github.com/Akshatavijapur92/blockchain-automation-framework.git
    ref: master
  releaseName: manufacturer-restserver
  values:
    metadata:
      namespace: manufacturer-net
    server:
      name: manufacturer-restserver
      port: 20001
      localmspid: manufacturerMSP
      image: index.docker.io/hyperledgerlabs/supplychain_fabric:rest_server_latest
      username: admin
      cert_path: "/secret/tls/admin.cert"
      key_path: "/secret/tls/admin.pem"
    storage:
      storageclassname: manufacturersc
      storagesize: 512Mi
    vault:
      address: http://aa2d78d17c76811eab25a02b991bc25b-1354633767.ap-south-1.elb.amazonaws.com:9000
      role: vault-role
      authpath: manufacturer-net-auth
      secretprefix: secret/crypto/peerOrganizations/manufacturer-net
      serviceaccountname: vault-auth
      imagesecretname: regcred
      image: hyperledgerlabs/alpine-utils:1.0
    service:
      servicetype: ClusterIP
      ports:
        apiPort: 20001
        targetPort: 8000
    connection:
      peer: peer0.manufacturer-net
      peerAddress: peer0.manufacturer-net
      peerPort: 7051
      ordererAddress: orderer1.fab.team19.aws.bafevent.com
      ordererPort: 8443