apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: manufacturer-net-ca
  namespace: manufacturer-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: manufacturer-net-ca
  chart:
    git: ssh://git@github.com/Akshatavijapur92/blockchain-automation-framework.git
    ref: master
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: manufacturer-net
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.4
    server:
      name: ca
      tlsstatus: true
      admin: manufacturer-admin
    storage:
      storageclassname: manufacturersc
      storagesize: 512Mi
    vault:
      role: vault-role
      address: http://aa2d78d17c76811eab25a02b991bc25b-1354633767.ap-south-1.elb.amazonaws.com:9000
      authpath: manufacturer-net-auth
      secretcert: secret/crypto/peerOrganizations/manufacturer-net/ca?ca.manufacturer-net-cert.pem
      secretkey: secret/crypto/peerOrganizations/manufacturer-net/ca?manufacturer-net-CA.key
      secretadminpass: secret/credentials/manufacturer-net/ca/manufacturer?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: haproxy
      type: peer
