apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-warehouse
  namespace: warehouse-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-warehouse
  chart:
    git: ssh://git@github.com/Akshatavijapur92/blockchain-automation-framework.git
    ref: master
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: warehouse-net
      images:
        fabrictools: hyperledger/fabric-tools:1.4.4
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.warehouse-net.fab.team19.aws.bafevent.com:8443
      localmspid: warehouseMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://aa2d78d17c76811eab25a02b991bc25b-1354633767.ap-south-1.elb.amazonaws.com:9000
      authpath: warehouse-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/warehouse-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/warehouse-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.fab.team19.aws.bafevent.com:8443
    anchorstx: |-
      CsACChAKDggCIgphbGxjaGFubmVsEqsCCqgCCgphbGxjaGFubmVsElwSWgoLQXBwbGljYXRpb24S
      SwgBEj8KDHdhcmVob3VzZU1TUBIvGgcKA01TUBIAIgsKB1JlYWRlcnMSACILCgdXcml0ZXJzEgAi
      CgoGQWRtaW5zEgAqBkFkbWlucxq7ARK4AQoLQXBwbGljYXRpb24SqAEIARKbAQoMd2FyZWhvdXNl
      TVNQEooBCAEaBwoDTVNQEgAaTwoLQW5jaG9yUGVlcnMSQBI2CjQKL3BlZXIwLndhcmVob3VzZS1u
      ZXQuZmFiLnRlYW0xOS5hd3MuYmFmZXZlbnQuY29tEPtBGgZBZG1pbnMiCwoHUmVhZGVycxIAIgsK
      B1dyaXRlcnMSACIKCgZBZG1pbnMSACoGQWRtaW5zKgZBZG1pbnM=

